#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SSITimeClockMgr")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblEmployee(tblEmployee instance);
  partial void UpdatetblEmployee(tblEmployee instance);
  partial void DeletetblEmployee(tblEmployee instance);
  partial void InserttblOutofOfficeDest(tblOutofOfficeDest instance);
  partial void UpdatetblOutofOfficeDest(tblOutofOfficeDest instance);
  partial void DeletetblOutofOfficeDest(tblOutofOfficeDest instance);
  partial void InserttblOutOfOfficeLog(tblOutOfOfficeLog instance);
  partial void UpdatetblOutOfOfficeLog(tblOutOfOfficeLog instance);
  partial void DeletetblOutOfOfficeLog(tblOutOfOfficeLog instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SSITimeClockMgrConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblEmployee> tblEmployees
	{
		get
		{
			return this.GetTable<tblEmployee>();
		}
	}
	
	public System.Data.Linq.Table<tblOutofOfficeDest> tblOutofOfficeDests
	{
		get
		{
			return this.GetTable<tblOutofOfficeDest>();
		}
	}
	
	public System.Data.Linq.Table<tblOutOfOfficeLog> tblOutOfOfficeLogs
	{
		get
		{
			return this.GetTable<tblOutOfOfficeLog>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee")]
public partial class tblEmployee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _EmployeeID;
	
	private string _EmployeeNumber;
	
	private string _LastName;
	
	private string _FirstName;
	
	private string _BadgeIDNumber;
	
	private string _EmployeeType;
	
	private string _DepartmentId;
	
	private bool _Active;
	
	private string _CompID;
	
	private System.Nullable<int> _EmployeeTypeID;
	
	private string _Note;
	
	private System.Nullable<System.DateTime> _HireDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnEmployeeNumberChanging(string value);
    partial void OnEmployeeNumberChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnBadgeIDNumberChanging(string value);
    partial void OnBadgeIDNumberChanged();
    partial void OnEmployeeTypeChanging(string value);
    partial void OnEmployeeTypeChanged();
    partial void OnDepartmentIdChanging(string value);
    partial void OnDepartmentIdChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnCompIDChanging(string value);
    partial void OnCompIDChanged();
    partial void OnEmployeeTypeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeTypeIDChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnHireDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHireDateChanged();
    #endregion
	
	public tblEmployee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeNumber", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string EmployeeNumber
	{
		get
		{
			return this._EmployeeNumber;
		}
		set
		{
			if ((this._EmployeeNumber != value))
			{
				this.OnEmployeeNumberChanging(value);
				this.SendPropertyChanging();
				this._EmployeeNumber = value;
				this.SendPropertyChanged("EmployeeNumber");
				this.OnEmployeeNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadgeIDNumber", DbType="VarChar(5)")]
	public string BadgeIDNumber
	{
		get
		{
			return this._BadgeIDNumber;
		}
		set
		{
			if ((this._BadgeIDNumber != value))
			{
				this.OnBadgeIDNumberChanging(value);
				this.SendPropertyChanging();
				this._BadgeIDNumber = value;
				this.SendPropertyChanged("BadgeIDNumber");
				this.OnBadgeIDNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string EmployeeType
	{
		get
		{
			return this._EmployeeType;
		}
		set
		{
			if ((this._EmployeeType != value))
			{
				this.OnEmployeeTypeChanging(value);
				this.SendPropertyChanging();
				this._EmployeeType = value;
				this.SendPropertyChanged("EmployeeType");
				this.OnEmployeeTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string DepartmentId
	{
		get
		{
			return this._DepartmentId;
		}
		set
		{
			if ((this._DepartmentId != value))
			{
				this.OnDepartmentIdChanging(value);
				this.SendPropertyChanging();
				this._DepartmentId = value;
				this.SendPropertyChanged("DepartmentId");
				this.OnDepartmentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
	public bool Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
	public string CompID
	{
		get
		{
			return this._CompID;
		}
		set
		{
			if ((this._CompID != value))
			{
				this.OnCompIDChanging(value);
				this.SendPropertyChanging();
				this._CompID = value;
				this.SendPropertyChanged("CompID");
				this.OnCompIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeID", DbType="Int")]
	public System.Nullable<int> EmployeeTypeID
	{
		get
		{
			return this._EmployeeTypeID;
		}
		set
		{
			if ((this._EmployeeTypeID != value))
			{
				this.OnEmployeeTypeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeTypeID = value;
				this.SendPropertyChanged("EmployeeTypeID");
				this.OnEmployeeTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="VarChar(255)")]
	public string Note
	{
		get
		{
			return this._Note;
		}
		set
		{
			if ((this._Note != value))
			{
				this.OnNoteChanging(value);
				this.SendPropertyChanging();
				this._Note = value;
				this.SendPropertyChanged("Note");
				this.OnNoteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HireDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> HireDate
	{
		get
		{
			return this._HireDate;
		}
		set
		{
			if ((this._HireDate != value))
			{
				this.OnHireDateChanging(value);
				this.SendPropertyChanging();
				this._HireDate = value;
				this.SendPropertyChanged("HireDate");
				this.OnHireDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOutofOfficeDest")]
public partial class tblOutofOfficeDest : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _ID;
	
	private string _Location_Code;
	
	private string _Location_Desc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnLocation_CodeChanging(string value);
    partial void OnLocation_CodeChanged();
    partial void OnLocation_DescChanging(string value);
    partial void OnLocation_DescChanged();
    #endregion
	
	public tblOutofOfficeDest()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Location_Code
	{
		get
		{
			return this._Location_Code;
		}
		set
		{
			if ((this._Location_Code != value))
			{
				this.OnLocation_CodeChanging(value);
				this.SendPropertyChanging();
				this._Location_Code = value;
				this.SendPropertyChanged("Location_Code");
				this.OnLocation_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Location_Desc
	{
		get
		{
			return this._Location_Desc;
		}
		set
		{
			if ((this._Location_Desc != value))
			{
				this.OnLocation_DescChanging(value);
				this.SendPropertyChanging();
				this._Location_Desc = value;
				this.SendPropertyChanged("Location_Desc");
				this.OnLocation_DescChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOutOfOfficeLog")]
public partial class tblOutOfOfficeLog : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _OutOfOfficeLogID;
	
	private int _EmployeeID;
	
	private string _OutOfOfficeDestID;
	
	private System.DateTime _DateTimeOut;
	
	private System.Nullable<System.DateTime> _DateTimeIn;
	
	private string _Dest_type;
	
	private string _Other_Desc;
	
	private string _Reason;
	
	private string _User_add;
	
	private string _IP_add;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOutOfOfficeLogIDChanging(int value);
    partial void OnOutOfOfficeLogIDChanged();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnOutOfOfficeDestIDChanging(string value);
    partial void OnOutOfOfficeDestIDChanged();
    partial void OnDateTimeOutChanging(System.DateTime value);
    partial void OnDateTimeOutChanged();
    partial void OnDateTimeInChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeInChanged();
    partial void OnDest_typeChanging(string value);
    partial void OnDest_typeChanged();
    partial void OnOther_DescChanging(string value);
    partial void OnOther_DescChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnUser_addChanging(string value);
    partial void OnUser_addChanged();
    partial void OnIP_addChanging(string value);
    partial void OnIP_addChanged();
    #endregion
	
	public tblOutOfOfficeLog()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutOfOfficeLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int OutOfOfficeLogID
	{
		get
		{
			return this._OutOfOfficeLogID;
		}
		set
		{
			if ((this._OutOfOfficeLogID != value))
			{
				this.OnOutOfOfficeLogIDChanging(value);
				this.SendPropertyChanging();
				this._OutOfOfficeLogID = value;
				this.SendPropertyChanged("OutOfOfficeLogID");
				this.OnOutOfOfficeLogIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int NOT NULL")]
	public int EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutOfOfficeDestID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string OutOfOfficeDestID
	{
		get
		{
			return this._OutOfOfficeDestID;
		}
		set
		{
			if ((this._OutOfOfficeDestID != value))
			{
				this.OnOutOfOfficeDestIDChanging(value);
				this.SendPropertyChanging();
				this._OutOfOfficeDestID = value;
				this.SendPropertyChanged("OutOfOfficeDestID");
				this.OnOutOfOfficeDestIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeOut", DbType="DateTime NOT NULL")]
	public System.DateTime DateTimeOut
	{
		get
		{
			return this._DateTimeOut;
		}
		set
		{
			if ((this._DateTimeOut != value))
			{
				this.OnDateTimeOutChanging(value);
				this.SendPropertyChanging();
				this._DateTimeOut = value;
				this.SendPropertyChanged("DateTimeOut");
				this.OnDateTimeOutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeIn", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateTimeIn
	{
		get
		{
			return this._DateTimeIn;
		}
		set
		{
			if ((this._DateTimeIn != value))
			{
				this.OnDateTimeInChanging(value);
				this.SendPropertyChanging();
				this._DateTimeIn = value;
				this.SendPropertyChanged("DateTimeIn");
				this.OnDateTimeInChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dest_type", DbType="VarChar(1)")]
	public string Dest_type
	{
		get
		{
			return this._Dest_type;
		}
		set
		{
			if ((this._Dest_type != value))
			{
				this.OnDest_typeChanging(value);
				this.SendPropertyChanging();
				this._Dest_type = value;
				this.SendPropertyChanged("Dest_type");
				this.OnDest_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_Desc", DbType="VarChar(200)")]
	public string Other_Desc
	{
		get
		{
			return this._Other_Desc;
		}
		set
		{
			if ((this._Other_Desc != value))
			{
				this.OnOther_DescChanging(value);
				this.SendPropertyChanging();
				this._Other_Desc = value;
				this.SendPropertyChanged("Other_Desc");
				this.OnOther_DescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this.OnReasonChanging(value);
				this.SendPropertyChanging();
				this._Reason = value;
				this.SendPropertyChanged("Reason");
				this.OnReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_add", DbType="VarChar(30)")]
	public string User_add
	{
		get
		{
			return this._User_add;
		}
		set
		{
			if ((this._User_add != value))
			{
				this.OnUser_addChanging(value);
				this.SendPropertyChanging();
				this._User_add = value;
				this.SendPropertyChanged("User_add");
				this.OnUser_addChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_add", DbType="VarChar(20)")]
	public string IP_add
	{
		get
		{
			return this._IP_add;
		}
		set
		{
			if ((this._IP_add != value))
			{
				this.OnIP_addChanging(value);
				this.SendPropertyChanging();
				this._IP_add = value;
				this.SendPropertyChanged("IP_add");
				this.OnIP_addChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
