#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rent Test")]
public partial class MenuSystemDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblSys_MenuFolder(tblSys_MenuFolder instance);
  partial void UpdatetblSys_MenuFolder(tblSys_MenuFolder instance);
  partial void DeletetblSys_MenuFolder(tblSys_MenuFolder instance);
  partial void InserttblSys_MenuChoice(tblSys_MenuChoice instance);
  partial void UpdatetblSys_MenuChoice(tblSys_MenuChoice instance);
  partial void DeletetblSys_MenuChoice(tblSys_MenuChoice instance);
  partial void InserttblSys_MenuChoice_Group_Matrix(tblSys_MenuChoice_Group_Matrix instance);
  partial void UpdatetblSys_MenuChoice_Group_Matrix(tblSys_MenuChoice_Group_Matrix instance);
  partial void DeletetblSys_MenuChoice_Group_Matrix(tblSys_MenuChoice_Group_Matrix instance);
  partial void InserttblSys_Group(tblSys_Group instance);
  partial void UpdatetblSys_Group(tblSys_Group instance);
  partial void DeletetblSys_Group(tblSys_Group instance);
  partial void InserttblSys_Group_User_Matrix(tblSys_Group_User_Matrix instance);
  partial void UpdatetblSys_Group_User_Matrix(tblSys_Group_User_Matrix instance);
  partial void DeletetblSys_Group_User_Matrix(tblSys_Group_User_Matrix instance);
  partial void InserttblSys_Folder_Group_Matrix(tblSys_Folder_Group_Matrix instance);
  partial void UpdatetblSys_Folder_Group_Matrix(tblSys_Folder_Group_Matrix instance);
  partial void DeletetblSys_Folder_Group_Matrix(tblSys_Folder_Group_Matrix instance);
  #endregion
	
	public MenuSystemDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Rent DevConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MenuSystemDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MenuSystemDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MenuSystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MenuSystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblSys_MenuFolder> tblSys_MenuFolders
	{
		get
		{
			return this.GetTable<tblSys_MenuFolder>();
		}
	}
	
	public System.Data.Linq.Table<tblSys_MenuChoice> tblSys_MenuChoices
	{
		get
		{
			return this.GetTable<tblSys_MenuChoice>();
		}
	}
	
	public System.Data.Linq.Table<tblSys_MenuChoice_Group_Matrix> tblSys_MenuChoice_Group_Matrixes
	{
		get
		{
			return this.GetTable<tblSys_MenuChoice_Group_Matrix>();
		}
	}
	
	public System.Data.Linq.Table<tblSys_Group> tblSys_Groups
	{
		get
		{
			return this.GetTable<tblSys_Group>();
		}
	}
	
	public System.Data.Linq.Table<tblSys_Group_User_Matrix> tblSys_Group_User_Matrixes
	{
		get
		{
			return this.GetTable<tblSys_Group_User_Matrix>();
		}
	}
	
	public System.Data.Linq.Table<tblSys_Folder_Group_Matrix> tblSys_Folder_Group_Matrixes
	{
		get
		{
			return this.GetTable<tblSys_Folder_Group_Matrix>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSys_MenuFolders")]
public partial class tblSys_MenuFolder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _FolderID;
	
	private string _FolderName;
	
	private System.Nullable<int> _SubOfID;
	
	private System.Nullable<short> _SmallIcon;
	
	private System.Nullable<short> _LargeIcon;
	
	private System.Nullable<short> _SortOrder;
	
	private System.Nullable<bool> _Web;
	
	private EntitySet<tblSys_MenuChoice> _tblSys_MenuChoices;
	
	private EntitySet<tblSys_Folder_Group_Matrix> _tblSys_Folder_Group_Matrixes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFolderIDChanging(int value);
    partial void OnFolderIDChanged();
    partial void OnFolderNameChanging(string value);
    partial void OnFolderNameChanged();
    partial void OnSubOfIDChanging(System.Nullable<int> value);
    partial void OnSubOfIDChanged();
    partial void OnSmallIconChanging(System.Nullable<short> value);
    partial void OnSmallIconChanged();
    partial void OnLargeIconChanging(System.Nullable<short> value);
    partial void OnLargeIconChanged();
    partial void OnSortOrderChanging(System.Nullable<short> value);
    partial void OnSortOrderChanged();
    partial void OnWebChanging(System.Nullable<bool> value);
    partial void OnWebChanged();
    #endregion
	
	public tblSys_MenuFolder()
	{
		this._tblSys_MenuChoices = new EntitySet<tblSys_MenuChoice>(new Action<tblSys_MenuChoice>(this.attach_tblSys_MenuChoices), new Action<tblSys_MenuChoice>(this.detach_tblSys_MenuChoices));
		this._tblSys_Folder_Group_Matrixes = new EntitySet<tblSys_Folder_Group_Matrix>(new Action<tblSys_Folder_Group_Matrix>(this.attach_tblSys_Folder_Group_Matrixes), new Action<tblSys_Folder_Group_Matrix>(this.detach_tblSys_Folder_Group_Matrixes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int FolderID
	{
		get
		{
			return this._FolderID;
		}
		set
		{
			if ((this._FolderID != value))
			{
				this.OnFolderIDChanging(value);
				this.SendPropertyChanging();
				this._FolderID = value;
				this.SendPropertyChanged("FolderID");
				this.OnFolderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderName", DbType="VarChar(50)")]
	public string FolderName
	{
		get
		{
			return this._FolderName;
		}
		set
		{
			if ((this._FolderName != value))
			{
				this.OnFolderNameChanging(value);
				this.SendPropertyChanging();
				this._FolderName = value;
				this.SendPropertyChanged("FolderName");
				this.OnFolderNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubOfID", DbType="Int")]
	public System.Nullable<int> SubOfID
	{
		get
		{
			return this._SubOfID;
		}
		set
		{
			if ((this._SubOfID != value))
			{
				this.OnSubOfIDChanging(value);
				this.SendPropertyChanging();
				this._SubOfID = value;
				this.SendPropertyChanged("SubOfID");
				this.OnSubOfIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallIcon", DbType="SmallInt")]
	public System.Nullable<short> SmallIcon
	{
		get
		{
			return this._SmallIcon;
		}
		set
		{
			if ((this._SmallIcon != value))
			{
				this.OnSmallIconChanging(value);
				this.SendPropertyChanging();
				this._SmallIcon = value;
				this.SendPropertyChanged("SmallIcon");
				this.OnSmallIconChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargeIcon", DbType="SmallInt")]
	public System.Nullable<short> LargeIcon
	{
		get
		{
			return this._LargeIcon;
		}
		set
		{
			if ((this._LargeIcon != value))
			{
				this.OnLargeIconChanging(value);
				this.SendPropertyChanging();
				this._LargeIcon = value;
				this.SendPropertyChanged("LargeIcon");
				this.OnLargeIconChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="SmallInt")]
	public System.Nullable<short> SortOrder
	{
		get
		{
			return this._SortOrder;
		}
		set
		{
			if ((this._SortOrder != value))
			{
				this.OnSortOrderChanging(value);
				this.SendPropertyChanging();
				this._SortOrder = value;
				this.SendPropertyChanged("SortOrder");
				this.OnSortOrderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="Bit")]
	public System.Nullable<bool> Web
	{
		get
		{
			return this._Web;
		}
		set
		{
			if ((this._Web != value))
			{
				this.OnWebChanging(value);
				this.SendPropertyChanging();
				this._Web = value;
				this.SendPropertyChanged("Web");
				this.OnWebChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_MenuFolder_tblSys_MenuChoice", Storage="_tblSys_MenuChoices", ThisKey="FolderID", OtherKey="FolderID")]
	public EntitySet<tblSys_MenuChoice> tblSys_MenuChoices
	{
		get
		{
			return this._tblSys_MenuChoices;
		}
		set
		{
			this._tblSys_MenuChoices.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_MenuFolder_tblSys_Folder_Group_Matrix", Storage="_tblSys_Folder_Group_Matrixes", ThisKey="FolderID", OtherKey="FolderID")]
	public EntitySet<tblSys_Folder_Group_Matrix> tblSys_Folder_Group_Matrixes
	{
		get
		{
			return this._tblSys_Folder_Group_Matrixes;
		}
		set
		{
			this._tblSys_Folder_Group_Matrixes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblSys_MenuChoices(tblSys_MenuChoice entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_MenuFolder = this;
	}
	
	private void detach_tblSys_MenuChoices(tblSys_MenuChoice entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_MenuFolder = null;
	}
	
	private void attach_tblSys_Folder_Group_Matrixes(tblSys_Folder_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_MenuFolder = this;
	}
	
	private void detach_tblSys_Folder_Group_Matrixes(tblSys_Folder_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_MenuFolder = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSys_MenuChoices")]
public partial class tblSys_MenuChoice : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MenuChoiceID;
	
	private string _MenuChoiceDescription;
	
	private int _FolderID;
	
	private System.Nullable<short> _SortOrder;
	
	private string _CommandLine;
	
	private System.Nullable<short> _RunType;
	
	private string _IconName;
	
	private System.Nullable<int> _SystemObjectID;
	
	private EntitySet<tblSys_MenuChoice_Group_Matrix> _tblSys_MenuChoice_Group_Matrixes;
	
	private EntityRef<tblSys_MenuFolder> _tblSys_MenuFolder;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuChoiceIDChanging(int value);
    partial void OnMenuChoiceIDChanged();
    partial void OnMenuChoiceDescriptionChanging(string value);
    partial void OnMenuChoiceDescriptionChanged();
    partial void OnFolderIDChanging(int value);
    partial void OnFolderIDChanged();
    partial void OnSortOrderChanging(System.Nullable<short> value);
    partial void OnSortOrderChanged();
    partial void OnCommandLineChanging(string value);
    partial void OnCommandLineChanged();
    partial void OnRunTypeChanging(System.Nullable<short> value);
    partial void OnRunTypeChanged();
    partial void OnIconNameChanging(string value);
    partial void OnIconNameChanged();
    partial void OnSystemObjectIDChanging(System.Nullable<int> value);
    partial void OnSystemObjectIDChanged();
    #endregion
	
	public tblSys_MenuChoice()
	{
		this._tblSys_MenuChoice_Group_Matrixes = new EntitySet<tblSys_MenuChoice_Group_Matrix>(new Action<tblSys_MenuChoice_Group_Matrix>(this.attach_tblSys_MenuChoice_Group_Matrixes), new Action<tblSys_MenuChoice_Group_Matrix>(this.detach_tblSys_MenuChoice_Group_Matrixes));
		this._tblSys_MenuFolder = default(EntityRef<tblSys_MenuFolder>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuChoiceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MenuChoiceID
	{
		get
		{
			return this._MenuChoiceID;
		}
		set
		{
			if ((this._MenuChoiceID != value))
			{
				this.OnMenuChoiceIDChanging(value);
				this.SendPropertyChanging();
				this._MenuChoiceID = value;
				this.SendPropertyChanged("MenuChoiceID");
				this.OnMenuChoiceIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuChoiceDescription", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MenuChoiceDescription
	{
		get
		{
			return this._MenuChoiceDescription;
		}
		set
		{
			if ((this._MenuChoiceDescription != value))
			{
				this.OnMenuChoiceDescriptionChanging(value);
				this.SendPropertyChanging();
				this._MenuChoiceDescription = value;
				this.SendPropertyChanged("MenuChoiceDescription");
				this.OnMenuChoiceDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderID", DbType="Int NOT NULL")]
	public int FolderID
	{
		get
		{
			return this._FolderID;
		}
		set
		{
			if ((this._FolderID != value))
			{
				if (this._tblSys_MenuFolder.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnFolderIDChanging(value);
				this.SendPropertyChanging();
				this._FolderID = value;
				this.SendPropertyChanged("FolderID");
				this.OnFolderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="SmallInt")]
	public System.Nullable<short> SortOrder
	{
		get
		{
			return this._SortOrder;
		}
		set
		{
			if ((this._SortOrder != value))
			{
				this.OnSortOrderChanging(value);
				this.SendPropertyChanging();
				this._SortOrder = value;
				this.SendPropertyChanged("SortOrder");
				this.OnSortOrderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommandLine", DbType="VarChar(255)")]
	public string CommandLine
	{
		get
		{
			return this._CommandLine;
		}
		set
		{
			if ((this._CommandLine != value))
			{
				this.OnCommandLineChanging(value);
				this.SendPropertyChanging();
				this._CommandLine = value;
				this.SendPropertyChanged("CommandLine");
				this.OnCommandLineChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunType", DbType="SmallInt")]
	public System.Nullable<short> RunType
	{
		get
		{
			return this._RunType;
		}
		set
		{
			if ((this._RunType != value))
			{
				this.OnRunTypeChanging(value);
				this.SendPropertyChanging();
				this._RunType = value;
				this.SendPropertyChanged("RunType");
				this.OnRunTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconName", DbType="VarChar(50)")]
	public string IconName
	{
		get
		{
			return this._IconName;
		}
		set
		{
			if ((this._IconName != value))
			{
				this.OnIconNameChanging(value);
				this.SendPropertyChanging();
				this._IconName = value;
				this.SendPropertyChanged("IconName");
				this.OnIconNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemObjectID", DbType="Int")]
	public System.Nullable<int> SystemObjectID
	{
		get
		{
			return this._SystemObjectID;
		}
		set
		{
			if ((this._SystemObjectID != value))
			{
				this.OnSystemObjectIDChanging(value);
				this.SendPropertyChanging();
				this._SystemObjectID = value;
				this.SendPropertyChanged("SystemObjectID");
				this.OnSystemObjectIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_MenuChoice_tblSys_MenuChoice_Group_Matrix", Storage="_tblSys_MenuChoice_Group_Matrixes", ThisKey="MenuChoiceID", OtherKey="MenuChoiceID")]
	public EntitySet<tblSys_MenuChoice_Group_Matrix> tblSys_MenuChoice_Group_Matrixes
	{
		get
		{
			return this._tblSys_MenuChoice_Group_Matrixes;
		}
		set
		{
			this._tblSys_MenuChoice_Group_Matrixes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_MenuFolder_tblSys_MenuChoice", Storage="_tblSys_MenuFolder", ThisKey="FolderID", OtherKey="FolderID", IsForeignKey=true)]
	public tblSys_MenuFolder tblSys_MenuFolder
	{
		get
		{
			return this._tblSys_MenuFolder.Entity;
		}
		set
		{
			tblSys_MenuFolder previousValue = this._tblSys_MenuFolder.Entity;
			if (((previousValue != value) 
						|| (this._tblSys_MenuFolder.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblSys_MenuFolder.Entity = null;
					previousValue.tblSys_MenuChoices.Remove(this);
				}
				this._tblSys_MenuFolder.Entity = value;
				if ((value != null))
				{
					value.tblSys_MenuChoices.Add(this);
					this._FolderID = value.FolderID;
				}
				else
				{
					this._FolderID = default(int);
				}
				this.SendPropertyChanged("tblSys_MenuFolder");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblSys_MenuChoice_Group_Matrixes(tblSys_MenuChoice_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_MenuChoice = this;
	}
	
	private void detach_tblSys_MenuChoice_Group_Matrixes(tblSys_MenuChoice_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_MenuChoice = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSys_MenuChoice_Group_Matrix")]
public partial class tblSys_MenuChoice_Group_Matrix : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MenuChoiceID;
	
	private int _GroupID;
	
	private EntityRef<tblSys_MenuChoice> _tblSys_MenuChoice;
	
	private EntityRef<tblSys_Group> _tblSys_Group;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuChoiceIDChanging(int value);
    partial void OnMenuChoiceIDChanged();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    #endregion
	
	public tblSys_MenuChoice_Group_Matrix()
	{
		this._tblSys_MenuChoice = default(EntityRef<tblSys_MenuChoice>);
		this._tblSys_Group = default(EntityRef<tblSys_Group>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuChoiceID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int MenuChoiceID
	{
		get
		{
			return this._MenuChoiceID;
		}
		set
		{
			if ((this._MenuChoiceID != value))
			{
				if (this._tblSys_MenuChoice.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMenuChoiceIDChanging(value);
				this.SendPropertyChanging();
				this._MenuChoiceID = value;
				this.SendPropertyChanged("MenuChoiceID");
				this.OnMenuChoiceIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int GroupID
	{
		get
		{
			return this._GroupID;
		}
		set
		{
			if ((this._GroupID != value))
			{
				if (this._tblSys_Group.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnGroupIDChanging(value);
				this.SendPropertyChanging();
				this._GroupID = value;
				this.SendPropertyChanged("GroupID");
				this.OnGroupIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_MenuChoice_tblSys_MenuChoice_Group_Matrix", Storage="_tblSys_MenuChoice", ThisKey="MenuChoiceID", OtherKey="MenuChoiceID", IsForeignKey=true)]
	public tblSys_MenuChoice tblSys_MenuChoice
	{
		get
		{
			return this._tblSys_MenuChoice.Entity;
		}
		set
		{
			tblSys_MenuChoice previousValue = this._tblSys_MenuChoice.Entity;
			if (((previousValue != value) 
						|| (this._tblSys_MenuChoice.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblSys_MenuChoice.Entity = null;
					previousValue.tblSys_MenuChoice_Group_Matrixes.Remove(this);
				}
				this._tblSys_MenuChoice.Entity = value;
				if ((value != null))
				{
					value.tblSys_MenuChoice_Group_Matrixes.Add(this);
					this._MenuChoiceID = value.MenuChoiceID;
				}
				else
				{
					this._MenuChoiceID = default(int);
				}
				this.SendPropertyChanged("tblSys_MenuChoice");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_Group_tblSys_MenuChoice_Group_Matrix", Storage="_tblSys_Group", ThisKey="GroupID", OtherKey="GroupID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public tblSys_Group tblSys_Group
	{
		get
		{
			return this._tblSys_Group.Entity;
		}
		set
		{
			tblSys_Group previousValue = this._tblSys_Group.Entity;
			if (((previousValue != value) 
						|| (this._tblSys_Group.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblSys_Group.Entity = null;
					previousValue.tblSys_MenuChoice_Group_Matrixes.Remove(this);
				}
				this._tblSys_Group.Entity = value;
				if ((value != null))
				{
					value.tblSys_MenuChoice_Group_Matrixes.Add(this);
					this._GroupID = value.GroupID;
				}
				else
				{
					this._GroupID = default(int);
				}
				this.SendPropertyChanged("tblSys_Group");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSys_Groups")]
public partial class tblSys_Group : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _GroupID;
	
	private string _GroupName;
	
	private bool _SystemReserved;
	
	private EntitySet<tblSys_MenuChoice_Group_Matrix> _tblSys_MenuChoice_Group_Matrixes;
	
	private EntitySet<tblSys_Group_User_Matrix> _tblSys_Group_User_Matrixes;
	
	private EntitySet<tblSys_Folder_Group_Matrix> _tblSys_Folder_Group_Matrixes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnSystemReservedChanging(bool value);
    partial void OnSystemReservedChanged();
    #endregion
	
	public tblSys_Group()
	{
		this._tblSys_MenuChoice_Group_Matrixes = new EntitySet<tblSys_MenuChoice_Group_Matrix>(new Action<tblSys_MenuChoice_Group_Matrix>(this.attach_tblSys_MenuChoice_Group_Matrixes), new Action<tblSys_MenuChoice_Group_Matrix>(this.detach_tblSys_MenuChoice_Group_Matrixes));
		this._tblSys_Group_User_Matrixes = new EntitySet<tblSys_Group_User_Matrix>(new Action<tblSys_Group_User_Matrix>(this.attach_tblSys_Group_User_Matrixes), new Action<tblSys_Group_User_Matrix>(this.detach_tblSys_Group_User_Matrixes));
		this._tblSys_Folder_Group_Matrixes = new EntitySet<tblSys_Folder_Group_Matrix>(new Action<tblSys_Folder_Group_Matrix>(this.attach_tblSys_Folder_Group_Matrixes), new Action<tblSys_Folder_Group_Matrix>(this.detach_tblSys_Folder_Group_Matrixes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int GroupID
	{
		get
		{
			return this._GroupID;
		}
		set
		{
			if ((this._GroupID != value))
			{
				this.OnGroupIDChanging(value);
				this.SendPropertyChanging();
				this._GroupID = value;
				this.SendPropertyChanged("GroupID");
				this.OnGroupIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="VarChar(50)")]
	public string GroupName
	{
		get
		{
			return this._GroupName;
		}
		set
		{
			if ((this._GroupName != value))
			{
				this.OnGroupNameChanging(value);
				this.SendPropertyChanging();
				this._GroupName = value;
				this.SendPropertyChanged("GroupName");
				this.OnGroupNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemReserved", DbType="Bit NOT NULL")]
	public bool SystemReserved
	{
		get
		{
			return this._SystemReserved;
		}
		set
		{
			if ((this._SystemReserved != value))
			{
				this.OnSystemReservedChanging(value);
				this.SendPropertyChanging();
				this._SystemReserved = value;
				this.SendPropertyChanged("SystemReserved");
				this.OnSystemReservedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_Group_tblSys_MenuChoice_Group_Matrix", Storage="_tblSys_MenuChoice_Group_Matrixes", ThisKey="GroupID", OtherKey="GroupID")]
	public EntitySet<tblSys_MenuChoice_Group_Matrix> tblSys_MenuChoice_Group_Matrixes
	{
		get
		{
			return this._tblSys_MenuChoice_Group_Matrixes;
		}
		set
		{
			this._tblSys_MenuChoice_Group_Matrixes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_Group_tblSys_Group_User_Matrix", Storage="_tblSys_Group_User_Matrixes", ThisKey="GroupID", OtherKey="GroupID")]
	public EntitySet<tblSys_Group_User_Matrix> tblSys_Group_User_Matrixes
	{
		get
		{
			return this._tblSys_Group_User_Matrixes;
		}
		set
		{
			this._tblSys_Group_User_Matrixes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_Group_tblSys_Folder_Group_Matrix", Storage="_tblSys_Folder_Group_Matrixes", ThisKey="GroupID", OtherKey="GroupID")]
	public EntitySet<tblSys_Folder_Group_Matrix> tblSys_Folder_Group_Matrixes
	{
		get
		{
			return this._tblSys_Folder_Group_Matrixes;
		}
		set
		{
			this._tblSys_Folder_Group_Matrixes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblSys_MenuChoice_Group_Matrixes(tblSys_MenuChoice_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_Group = this;
	}
	
	private void detach_tblSys_MenuChoice_Group_Matrixes(tblSys_MenuChoice_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_Group = null;
	}
	
	private void attach_tblSys_Group_User_Matrixes(tblSys_Group_User_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_Group = this;
	}
	
	private void detach_tblSys_Group_User_Matrixes(tblSys_Group_User_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_Group = null;
	}
	
	private void attach_tblSys_Folder_Group_Matrixes(tblSys_Folder_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_Group = this;
	}
	
	private void detach_tblSys_Folder_Group_Matrixes(tblSys_Folder_Group_Matrix entity)
	{
		this.SendPropertyChanging();
		entity.tblSys_Group = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSys_Group_User_Matrix")]
public partial class tblSys_Group_User_Matrix : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UserID;
	
	private int _GroupID;
	
	private EntityRef<tblSys_Group> _tblSys_Group;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    #endregion
	
	public tblSys_Group_User_Matrix()
	{
		this._tblSys_Group = default(EntityRef<tblSys_Group>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int GroupID
	{
		get
		{
			return this._GroupID;
		}
		set
		{
			if ((this._GroupID != value))
			{
				if (this._tblSys_Group.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnGroupIDChanging(value);
				this.SendPropertyChanging();
				this._GroupID = value;
				this.SendPropertyChanged("GroupID");
				this.OnGroupIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_Group_tblSys_Group_User_Matrix", Storage="_tblSys_Group", ThisKey="GroupID", OtherKey="GroupID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public tblSys_Group tblSys_Group
	{
		get
		{
			return this._tblSys_Group.Entity;
		}
		set
		{
			tblSys_Group previousValue = this._tblSys_Group.Entity;
			if (((previousValue != value) 
						|| (this._tblSys_Group.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblSys_Group.Entity = null;
					previousValue.tblSys_Group_User_Matrixes.Remove(this);
				}
				this._tblSys_Group.Entity = value;
				if ((value != null))
				{
					value.tblSys_Group_User_Matrixes.Add(this);
					this._GroupID = value.GroupID;
				}
				else
				{
					this._GroupID = default(int);
				}
				this.SendPropertyChanged("tblSys_Group");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSys_Folder_Group_Matrix")]
public partial class tblSys_Folder_Group_Matrix : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _GroupID;
	
	private int _FolderID;
	
	private EntityRef<tblSys_Group> _tblSys_Group;
	
	private EntityRef<tblSys_MenuFolder> _tblSys_MenuFolder;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnFolderIDChanging(int value);
    partial void OnFolderIDChanged();
    #endregion
	
	public tblSys_Folder_Group_Matrix()
	{
		this._tblSys_Group = default(EntityRef<tblSys_Group>);
		this._tblSys_MenuFolder = default(EntityRef<tblSys_MenuFolder>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int GroupID
	{
		get
		{
			return this._GroupID;
		}
		set
		{
			if ((this._GroupID != value))
			{
				if (this._tblSys_Group.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnGroupIDChanging(value);
				this.SendPropertyChanging();
				this._GroupID = value;
				this.SendPropertyChanged("GroupID");
				this.OnGroupIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int FolderID
	{
		get
		{
			return this._FolderID;
		}
		set
		{
			if ((this._FolderID != value))
			{
				if (this._tblSys_MenuFolder.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnFolderIDChanging(value);
				this.SendPropertyChanging();
				this._FolderID = value;
				this.SendPropertyChanged("FolderID");
				this.OnFolderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_Group_tblSys_Folder_Group_Matrix", Storage="_tblSys_Group", ThisKey="GroupID", OtherKey="GroupID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public tblSys_Group tblSys_Group
	{
		get
		{
			return this._tblSys_Group.Entity;
		}
		set
		{
			tblSys_Group previousValue = this._tblSys_Group.Entity;
			if (((previousValue != value) 
						|| (this._tblSys_Group.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblSys_Group.Entity = null;
					previousValue.tblSys_Folder_Group_Matrixes.Remove(this);
				}
				this._tblSys_Group.Entity = value;
				if ((value != null))
				{
					value.tblSys_Folder_Group_Matrixes.Add(this);
					this._GroupID = value.GroupID;
				}
				else
				{
					this._GroupID = default(int);
				}
				this.SendPropertyChanged("tblSys_Group");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSys_MenuFolder_tblSys_Folder_Group_Matrix", Storage="_tblSys_MenuFolder", ThisKey="FolderID", OtherKey="FolderID", IsForeignKey=true)]
	public tblSys_MenuFolder tblSys_MenuFolder
	{
		get
		{
			return this._tblSys_MenuFolder.Entity;
		}
		set
		{
			tblSys_MenuFolder previousValue = this._tblSys_MenuFolder.Entity;
			if (((previousValue != value) 
						|| (this._tblSys_MenuFolder.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblSys_MenuFolder.Entity = null;
					previousValue.tblSys_Folder_Group_Matrixes.Remove(this);
				}
				this._tblSys_MenuFolder.Entity = value;
				if ((value != null))
				{
					value.tblSys_Folder_Group_Matrixes.Add(this);
					this._FolderID = value.FolderID;
				}
				else
				{
					this._FolderID = default(int);
				}
				this.SendPropertyChanged("tblSys_MenuFolder");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
