#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rent Publish")]
public partial class RentLinqClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblCustomer(tblCustomer instance);
  partial void UpdatetblCustomer(tblCustomer instance);
  partial void DeletetblCustomer(tblCustomer instance);
  partial void InserttblVendor(tblVendor instance);
  partial void UpdatetblVendor(tblVendor instance);
  partial void DeletetblVendor(tblVendor instance);
  #endregion
	
	public RentLinqClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Rent_PublishConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public RentLinqClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public RentLinqClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public RentLinqClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public RentLinqClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblCustomer> tblCustomers
	{
		get
		{
			return this.GetTable<tblCustomer>();
		}
	}
	
	public System.Data.Linq.Table<tblVendor> tblVendors
	{
		get
		{
			return this.GetTable<tblVendor>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCustomers")]
public partial class tblCustomer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Nullable<int> _Gen_NOTES;
	
	private string _Customer_Number;
	
	private string _Customer_Name;
	
	private string _Address_1;
	
	private string _Address_2;
	
	private string _City;
	
	private string _State;
	
	private string _Zip;
	
	private string _Contact;
	
	private string _Phone_Number;
	
	private string _Tax_Code;
	
	private string _Fax;
	
	private string _NOTES;
	
	private string _Toll_Free_Number;
	
	private string _Pager_Number;
	
	private string _Home_Number;
	
	private string _Tax_ID;
	
	private string _Department;
	
	private string _Type;
	
	private string _Terms;
	
	private bool _HasSpecialPriceBook;
	
	private string _Vendor_ID;
	
	private string _Supreme_EDI_ID;
	
	private string _Buyer_ID;
	
	private int _CustomerID;
	
	private bool _Active;
	
	private System.Nullable<int> _CustomerTypeID;
	
	private System.Nullable<bool> _Template;
	
	private string _EDIApproverID;
	
	private string _EDIPONumber;
	
	private System.Nullable<bool> _EDICustomer;
	
	private string _EDIFileCreateLocation;
	
	private string _EDIRunProcedure;
	
	private string _EDIFileFieldNameTitle;
	
	private string _EDINonCatalogNumber;
	
	private System.Nullable<int> _ParentCustomerID;
	
	private System.Nullable<bool> _UseParentPricing;
	
	private System.Nullable<bool> _PassedCreditCheck;
	
	private System.Nullable<int> _CreditCheckUserID;
	
	private System.Nullable<System.DateTime> _CreditCheckDate;
	
	private System.Nullable<int> _CustomerStatusID;
	
	private System.Nullable<int> _CreateUserID;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	private System.Nullable<bool> _ShowPCOnInvoice;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGen_NOTESChanging(System.Nullable<int> value);
    partial void OnGen_NOTESChanged();
    partial void OnCustomer_NumberChanging(string value);
    partial void OnCustomer_NumberChanged();
    partial void OnCustomer_NameChanging(string value);
    partial void OnCustomer_NameChanged();
    partial void OnAddress_1Changing(string value);
    partial void OnAddress_1Changed();
    partial void OnAddress_2Changing(string value);
    partial void OnAddress_2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnTax_CodeChanging(string value);
    partial void OnTax_CodeChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnNOTESChanging(string value);
    partial void OnNOTESChanged();
    partial void OnToll_Free_NumberChanging(string value);
    partial void OnToll_Free_NumberChanged();
    partial void OnPager_NumberChanging(string value);
    partial void OnPager_NumberChanged();
    partial void OnHome_NumberChanging(string value);
    partial void OnHome_NumberChanged();
    partial void OnTax_IDChanging(string value);
    partial void OnTax_IDChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTermsChanging(string value);
    partial void OnTermsChanged();
    partial void OnHasSpecialPriceBookChanging(bool value);
    partial void OnHasSpecialPriceBookChanged();
    partial void OnVendor_IDChanging(string value);
    partial void OnVendor_IDChanged();
    partial void OnSupreme_EDI_IDChanging(string value);
    partial void OnSupreme_EDI_IDChanged();
    partial void OnBuyer_IDChanging(string value);
    partial void OnBuyer_IDChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnCustomerTypeIDChanging(System.Nullable<int> value);
    partial void OnCustomerTypeIDChanged();
    partial void OnTemplateChanging(System.Nullable<bool> value);
    partial void OnTemplateChanged();
    partial void OnEDIApproverIDChanging(string value);
    partial void OnEDIApproverIDChanged();
    partial void OnEDIPONumberChanging(string value);
    partial void OnEDIPONumberChanged();
    partial void OnEDICustomerChanging(System.Nullable<bool> value);
    partial void OnEDICustomerChanged();
    partial void OnEDIFileCreateLocationChanging(string value);
    partial void OnEDIFileCreateLocationChanged();
    partial void OnEDIRunProcedureChanging(string value);
    partial void OnEDIRunProcedureChanged();
    partial void OnEDIFileFieldNameTitleChanging(string value);
    partial void OnEDIFileFieldNameTitleChanged();
    partial void OnEDINonCatalogNumberChanging(string value);
    partial void OnEDINonCatalogNumberChanged();
    partial void OnParentCustomerIDChanging(System.Nullable<int> value);
    partial void OnParentCustomerIDChanged();
    partial void OnUseParentPricingChanging(System.Nullable<bool> value);
    partial void OnUseParentPricingChanged();
    partial void OnPassedCreditCheckChanging(System.Nullable<bool> value);
    partial void OnPassedCreditCheckChanged();
    partial void OnCreditCheckUserIDChanging(System.Nullable<int> value);
    partial void OnCreditCheckUserIDChanged();
    partial void OnCreditCheckDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreditCheckDateChanged();
    partial void OnCustomerStatusIDChanging(System.Nullable<int> value);
    partial void OnCustomerStatusIDChanged();
    partial void OnCreateUserIDChanging(System.Nullable<int> value);
    partial void OnCreateUserIDChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnShowPCOnInvoiceChanging(System.Nullable<bool> value);
    partial void OnShowPCOnInvoiceChanged();
    #endregion
	
	public tblCustomer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gen_NOTES", DbType="Int")]
	public System.Nullable<int> Gen_NOTES
	{
		get
		{
			return this._Gen_NOTES;
		}
		set
		{
			if ((this._Gen_NOTES != value))
			{
				this.OnGen_NOTESChanging(value);
				this.SendPropertyChanging();
				this._Gen_NOTES = value;
				this.SendPropertyChanged("Gen_NOTES");
				this.OnGen_NOTESChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Number]", Storage="_Customer_Number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Customer_Number
	{
		get
		{
			return this._Customer_Number;
		}
		set
		{
			if ((this._Customer_Number != value))
			{
				this.OnCustomer_NumberChanging(value);
				this.SendPropertyChanging();
				this._Customer_Number = value;
				this.SendPropertyChanged("Customer_Number");
				this.OnCustomer_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Name]", Storage="_Customer_Name", DbType="VarChar(50)")]
	public string Customer_Name
	{
		get
		{
			return this._Customer_Name;
		}
		set
		{
			if ((this._Customer_Name != value))
			{
				this.OnCustomer_NameChanging(value);
				this.SendPropertyChanging();
				this._Customer_Name = value;
				this.SendPropertyChanged("Customer_Name");
				this.OnCustomer_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Address 1]", Storage="_Address_1", DbType="VarChar(50)")]
	public string Address_1
	{
		get
		{
			return this._Address_1;
		}
		set
		{
			if ((this._Address_1 != value))
			{
				this.OnAddress_1Changing(value);
				this.SendPropertyChanging();
				this._Address_1 = value;
				this.SendPropertyChanged("Address_1");
				this.OnAddress_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Address 2]", Storage="_Address_2", DbType="VarChar(50)")]
	public string Address_2
	{
		get
		{
			return this._Address_2;
		}
		set
		{
			if ((this._Address_2 != value))
			{
				this.OnAddress_2Changing(value);
				this.SendPropertyChanging();
				this._Address_2 = value;
				this.SendPropertyChanged("Address_2");
				this.OnAddress_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(50)")]
	public string Zip
	{
		get
		{
			return this._Zip;
		}
		set
		{
			if ((this._Zip != value))
			{
				this.OnZipChanging(value);
				this.SendPropertyChanging();
				this._Zip = value;
				this.SendPropertyChanged("Zip");
				this.OnZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(50)")]
	public string Contact
	{
		get
		{
			return this._Contact;
		}
		set
		{
			if ((this._Contact != value))
			{
				this.OnContactChanging(value);
				this.SendPropertyChanging();
				this._Contact = value;
				this.SendPropertyChanged("Contact");
				this.OnContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone Number]", Storage="_Phone_Number", DbType="VarChar(50)")]
	public string Phone_Number
	{
		get
		{
			return this._Phone_Number;
		}
		set
		{
			if ((this._Phone_Number != value))
			{
				this.OnPhone_NumberChanging(value);
				this.SendPropertyChanging();
				this._Phone_Number = value;
				this.SendPropertyChanged("Phone_Number");
				this.OnPhone_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tax Code]", Storage="_Tax_Code", DbType="VarChar(50)")]
	public string Tax_Code
	{
		get
		{
			return this._Tax_Code;
		}
		set
		{
			if ((this._Tax_Code != value))
			{
				this.OnTax_CodeChanging(value);
				this.SendPropertyChanging();
				this._Tax_Code = value;
				this.SendPropertyChanged("Tax_Code");
				this.OnTax_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(50)")]
	public string Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this.OnFaxChanging(value);
				this.SendPropertyChanging();
				this._Fax = value;
				this.SendPropertyChanged("Fax");
				this.OnFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string NOTES
	{
		get
		{
			return this._NOTES;
		}
		set
		{
			if ((this._NOTES != value))
			{
				this.OnNOTESChanging(value);
				this.SendPropertyChanging();
				this._NOTES = value;
				this.SendPropertyChanged("NOTES");
				this.OnNOTESChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Toll Free Number]", Storage="_Toll_Free_Number", DbType="VarChar(50)")]
	public string Toll_Free_Number
	{
		get
		{
			return this._Toll_Free_Number;
		}
		set
		{
			if ((this._Toll_Free_Number != value))
			{
				this.OnToll_Free_NumberChanging(value);
				this.SendPropertyChanging();
				this._Toll_Free_Number = value;
				this.SendPropertyChanged("Toll_Free_Number");
				this.OnToll_Free_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pager Number]", Storage="_Pager_Number", DbType="VarChar(50)")]
	public string Pager_Number
	{
		get
		{
			return this._Pager_Number;
		}
		set
		{
			if ((this._Pager_Number != value))
			{
				this.OnPager_NumberChanging(value);
				this.SendPropertyChanging();
				this._Pager_Number = value;
				this.SendPropertyChanged("Pager_Number");
				this.OnPager_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Home Number]", Storage="_Home_Number", DbType="VarChar(50)")]
	public string Home_Number
	{
		get
		{
			return this._Home_Number;
		}
		set
		{
			if ((this._Home_Number != value))
			{
				this.OnHome_NumberChanging(value);
				this.SendPropertyChanging();
				this._Home_Number = value;
				this.SendPropertyChanged("Home_Number");
				this.OnHome_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tax ID]", Storage="_Tax_ID", DbType="VarChar(50)")]
	public string Tax_ID
	{
		get
		{
			return this._Tax_ID;
		}
		set
		{
			if ((this._Tax_ID != value))
			{
				this.OnTax_IDChanging(value);
				this.SendPropertyChanging();
				this._Tax_ID = value;
				this.SendPropertyChanged("Tax_ID");
				this.OnTax_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(50)")]
	public string Department
	{
		get
		{
			return this._Department;
		}
		set
		{
			if ((this._Department != value))
			{
				this.OnDepartmentChanging(value);
				this.SendPropertyChanging();
				this._Department = value;
				this.SendPropertyChanged("Department");
				this.OnDepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="VarChar(50)")]
	public string Terms
	{
		get
		{
			return this._Terms;
		}
		set
		{
			if ((this._Terms != value))
			{
				this.OnTermsChanging(value);
				this.SendPropertyChanging();
				this._Terms = value;
				this.SendPropertyChanged("Terms");
				this.OnTermsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasSpecialPriceBook", DbType="Bit NOT NULL")]
	public bool HasSpecialPriceBook
	{
		get
		{
			return this._HasSpecialPriceBook;
		}
		set
		{
			if ((this._HasSpecialPriceBook != value))
			{
				this.OnHasSpecialPriceBookChanging(value);
				this.SendPropertyChanging();
				this._HasSpecialPriceBook = value;
				this.SendPropertyChanged("HasSpecialPriceBook");
				this.OnHasSpecialPriceBookChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vendor ID]", Storage="_Vendor_ID", DbType="VarChar(50)")]
	public string Vendor_ID
	{
		get
		{
			return this._Vendor_ID;
		}
		set
		{
			if ((this._Vendor_ID != value))
			{
				this.OnVendor_IDChanging(value);
				this.SendPropertyChanging();
				this._Vendor_ID = value;
				this.SendPropertyChanged("Vendor_ID");
				this.OnVendor_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Supreme EDI ID]", Storage="_Supreme_EDI_ID", DbType="VarChar(50)")]
	public string Supreme_EDI_ID
	{
		get
		{
			return this._Supreme_EDI_ID;
		}
		set
		{
			if ((this._Supreme_EDI_ID != value))
			{
				this.OnSupreme_EDI_IDChanging(value);
				this.SendPropertyChanging();
				this._Supreme_EDI_ID = value;
				this.SendPropertyChanged("Supreme_EDI_ID");
				this.OnSupreme_EDI_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Buyer ID]", Storage="_Buyer_ID", DbType="VarChar(50)")]
	public string Buyer_ID
	{
		get
		{
			return this._Buyer_ID;
		}
		set
		{
			if ((this._Buyer_ID != value))
			{
				this.OnBuyer_IDChanging(value);
				this.SendPropertyChanging();
				this._Buyer_ID = value;
				this.SendPropertyChanged("Buyer_ID");
				this.OnBuyer_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CustomerID
	{
		get
		{
			return this._CustomerID;
		}
		set
		{
			if ((this._CustomerID != value))
			{
				this.OnCustomerIDChanging(value);
				this.SendPropertyChanging();
				this._CustomerID = value;
				this.SendPropertyChanged("CustomerID");
				this.OnCustomerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
	public bool Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerTypeID", DbType="Int")]
	public System.Nullable<int> CustomerTypeID
	{
		get
		{
			return this._CustomerTypeID;
		}
		set
		{
			if ((this._CustomerTypeID != value))
			{
				this.OnCustomerTypeIDChanging(value);
				this.SendPropertyChanging();
				this._CustomerTypeID = value;
				this.SendPropertyChanged("CustomerTypeID");
				this.OnCustomerTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Template", DbType="Bit")]
	public System.Nullable<bool> Template
	{
		get
		{
			return this._Template;
		}
		set
		{
			if ((this._Template != value))
			{
				this.OnTemplateChanging(value);
				this.SendPropertyChanging();
				this._Template = value;
				this.SendPropertyChanged("Template");
				this.OnTemplateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIApproverID", DbType="VarChar(50)")]
	public string EDIApproverID
	{
		get
		{
			return this._EDIApproverID;
		}
		set
		{
			if ((this._EDIApproverID != value))
			{
				this.OnEDIApproverIDChanging(value);
				this.SendPropertyChanging();
				this._EDIApproverID = value;
				this.SendPropertyChanged("EDIApproverID");
				this.OnEDIApproverIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIPONumber", DbType="VarChar(50)")]
	public string EDIPONumber
	{
		get
		{
			return this._EDIPONumber;
		}
		set
		{
			if ((this._EDIPONumber != value))
			{
				this.OnEDIPONumberChanging(value);
				this.SendPropertyChanging();
				this._EDIPONumber = value;
				this.SendPropertyChanged("EDIPONumber");
				this.OnEDIPONumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDICustomer", DbType="Bit")]
	public System.Nullable<bool> EDICustomer
	{
		get
		{
			return this._EDICustomer;
		}
		set
		{
			if ((this._EDICustomer != value))
			{
				this.OnEDICustomerChanging(value);
				this.SendPropertyChanging();
				this._EDICustomer = value;
				this.SendPropertyChanged("EDICustomer");
				this.OnEDICustomerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIFileCreateLocation", DbType="VarChar(255)")]
	public string EDIFileCreateLocation
	{
		get
		{
			return this._EDIFileCreateLocation;
		}
		set
		{
			if ((this._EDIFileCreateLocation != value))
			{
				this.OnEDIFileCreateLocationChanging(value);
				this.SendPropertyChanging();
				this._EDIFileCreateLocation = value;
				this.SendPropertyChanged("EDIFileCreateLocation");
				this.OnEDIFileCreateLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIRunProcedure", DbType="VarChar(50)")]
	public string EDIRunProcedure
	{
		get
		{
			return this._EDIRunProcedure;
		}
		set
		{
			if ((this._EDIRunProcedure != value))
			{
				this.OnEDIRunProcedureChanging(value);
				this.SendPropertyChanging();
				this._EDIRunProcedure = value;
				this.SendPropertyChanged("EDIRunProcedure");
				this.OnEDIRunProcedureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIFileFieldNameTitle", DbType="VarChar(50)")]
	public string EDIFileFieldNameTitle
	{
		get
		{
			return this._EDIFileFieldNameTitle;
		}
		set
		{
			if ((this._EDIFileFieldNameTitle != value))
			{
				this.OnEDIFileFieldNameTitleChanging(value);
				this.SendPropertyChanging();
				this._EDIFileFieldNameTitle = value;
				this.SendPropertyChanged("EDIFileFieldNameTitle");
				this.OnEDIFileFieldNameTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDINonCatalogNumber", DbType="VarChar(50)")]
	public string EDINonCatalogNumber
	{
		get
		{
			return this._EDINonCatalogNumber;
		}
		set
		{
			if ((this._EDINonCatalogNumber != value))
			{
				this.OnEDINonCatalogNumberChanging(value);
				this.SendPropertyChanging();
				this._EDINonCatalogNumber = value;
				this.SendPropertyChanged("EDINonCatalogNumber");
				this.OnEDINonCatalogNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCustomerID", DbType="Int")]
	public System.Nullable<int> ParentCustomerID
	{
		get
		{
			return this._ParentCustomerID;
		}
		set
		{
			if ((this._ParentCustomerID != value))
			{
				this.OnParentCustomerIDChanging(value);
				this.SendPropertyChanging();
				this._ParentCustomerID = value;
				this.SendPropertyChanged("ParentCustomerID");
				this.OnParentCustomerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseParentPricing", DbType="Bit")]
	public System.Nullable<bool> UseParentPricing
	{
		get
		{
			return this._UseParentPricing;
		}
		set
		{
			if ((this._UseParentPricing != value))
			{
				this.OnUseParentPricingChanging(value);
				this.SendPropertyChanging();
				this._UseParentPricing = value;
				this.SendPropertyChanged("UseParentPricing");
				this.OnUseParentPricingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassedCreditCheck", DbType="Bit")]
	public System.Nullable<bool> PassedCreditCheck
	{
		get
		{
			return this._PassedCreditCheck;
		}
		set
		{
			if ((this._PassedCreditCheck != value))
			{
				this.OnPassedCreditCheckChanging(value);
				this.SendPropertyChanging();
				this._PassedCreditCheck = value;
				this.SendPropertyChanged("PassedCreditCheck");
				this.OnPassedCreditCheckChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCheckUserID", DbType="Int")]
	public System.Nullable<int> CreditCheckUserID
	{
		get
		{
			return this._CreditCheckUserID;
		}
		set
		{
			if ((this._CreditCheckUserID != value))
			{
				this.OnCreditCheckUserIDChanging(value);
				this.SendPropertyChanging();
				this._CreditCheckUserID = value;
				this.SendPropertyChanged("CreditCheckUserID");
				this.OnCreditCheckUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCheckDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreditCheckDate
	{
		get
		{
			return this._CreditCheckDate;
		}
		set
		{
			if ((this._CreditCheckDate != value))
			{
				this.OnCreditCheckDateChanging(value);
				this.SendPropertyChanging();
				this._CreditCheckDate = value;
				this.SendPropertyChanged("CreditCheckDate");
				this.OnCreditCheckDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerStatusID", DbType="Int")]
	public System.Nullable<int> CustomerStatusID
	{
		get
		{
			return this._CustomerStatusID;
		}
		set
		{
			if ((this._CustomerStatusID != value))
			{
				this.OnCustomerStatusIDChanging(value);
				this.SendPropertyChanging();
				this._CustomerStatusID = value;
				this.SendPropertyChanged("CustomerStatusID");
				this.OnCustomerStatusIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="Int")]
	public System.Nullable<int> CreateUserID
	{
		get
		{
			return this._CreateUserID;
		}
		set
		{
			if ((this._CreateUserID != value))
			{
				this.OnCreateUserIDChanging(value);
				this.SendPropertyChanging();
				this._CreateUserID = value;
				this.SendPropertyChanged("CreateUserID");
				this.OnCreateUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowPCOnInvoice", DbType="Bit")]
	public System.Nullable<bool> ShowPCOnInvoice
	{
		get
		{
			return this._ShowPCOnInvoice;
		}
		set
		{
			if ((this._ShowPCOnInvoice != value))
			{
				this.OnShowPCOnInvoiceChanging(value);
				this.SendPropertyChanging();
				this._ShowPCOnInvoice = value;
				this.SendPropertyChanged("ShowPCOnInvoice");
				this.OnShowPCOnInvoiceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVendors")]
public partial class tblVendor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _VendorID;
	
	private string _VendorName;
	
	private string _Address1;
	
	private string _Address2;
	
	private string _City;
	
	private string _State;
	
	private string _PostalCode;
	
	private System.Nullable<int> _TermsID;
	
	private System.Nullable<float> _DefaultDiscount;
	
	private string _Contact;
	
	private System.Nullable<bool> _POVendor;
	
	private string _VendorNumber;
	
	private string _Phone;
	
	private string _Fax;
	
	private System.Nullable<int> _DefaultPODocumentCodeID;
	
	private bool _TCVendor;
	
	private System.Nullable<int> _ApprovedVendorTypeID;
	
	private string _ContactEmailAddress;
	
	private System.Nullable<int> _CreateUserID;
	
	private System.Nullable<System.DateTime> _CreateDateTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVendorIDChanging(int value);
    partial void OnVendorIDChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnTermsIDChanging(System.Nullable<int> value);
    partial void OnTermsIDChanged();
    partial void OnDefaultDiscountChanging(System.Nullable<float> value);
    partial void OnDefaultDiscountChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnPOVendorChanging(System.Nullable<bool> value);
    partial void OnPOVendorChanged();
    partial void OnVendorNumberChanging(string value);
    partial void OnVendorNumberChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnDefaultPODocumentCodeIDChanging(System.Nullable<int> value);
    partial void OnDefaultPODocumentCodeIDChanged();
    partial void OnTCVendorChanging(bool value);
    partial void OnTCVendorChanged();
    partial void OnApprovedVendorTypeIDChanging(System.Nullable<int> value);
    partial void OnApprovedVendorTypeIDChanged();
    partial void OnContactEmailAddressChanging(string value);
    partial void OnContactEmailAddressChanged();
    partial void OnCreateUserIDChanging(System.Nullable<int> value);
    partial void OnCreateUserIDChanged();
    partial void OnCreateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateTimeChanged();
    #endregion
	
	public tblVendor()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int VendorID
	{
		get
		{
			return this._VendorID;
		}
		set
		{
			if ((this._VendorID != value))
			{
				this.OnVendorIDChanging(value);
				this.SendPropertyChanging();
				this._VendorID = value;
				this.SendPropertyChanged("VendorID");
				this.OnVendorIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(50)")]
	public string VendorName
	{
		get
		{
			return this._VendorName;
		}
		set
		{
			if ((this._VendorName != value))
			{
				this.OnVendorNameChanging(value);
				this.SendPropertyChanging();
				this._VendorName = value;
				this.SendPropertyChanged("VendorName");
				this.OnVendorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(50)")]
	public string Address1
	{
		get
		{
			return this._Address1;
		}
		set
		{
			if ((this._Address1 != value))
			{
				this.OnAddress1Changing(value);
				this.SendPropertyChanging();
				this._Address1 = value;
				this.SendPropertyChanged("Address1");
				this.OnAddress1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(50)")]
	public string Address2
	{
		get
		{
			return this._Address2;
		}
		set
		{
			if ((this._Address2 != value))
			{
				this.OnAddress2Changing(value);
				this.SendPropertyChanging();
				this._Address2 = value;
				this.SendPropertyChanged("Address2");
				this.OnAddress2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(2)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(15)")]
	public string PostalCode
	{
		get
		{
			return this._PostalCode;
		}
		set
		{
			if ((this._PostalCode != value))
			{
				this.OnPostalCodeChanging(value);
				this.SendPropertyChanging();
				this._PostalCode = value;
				this.SendPropertyChanged("PostalCode");
				this.OnPostalCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermsID", DbType="Int")]
	public System.Nullable<int> TermsID
	{
		get
		{
			return this._TermsID;
		}
		set
		{
			if ((this._TermsID != value))
			{
				this.OnTermsIDChanging(value);
				this.SendPropertyChanging();
				this._TermsID = value;
				this.SendPropertyChanged("TermsID");
				this.OnTermsIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultDiscount", DbType="Real")]
	public System.Nullable<float> DefaultDiscount
	{
		get
		{
			return this._DefaultDiscount;
		}
		set
		{
			if ((this._DefaultDiscount != value))
			{
				this.OnDefaultDiscountChanging(value);
				this.SendPropertyChanging();
				this._DefaultDiscount = value;
				this.SendPropertyChanged("DefaultDiscount");
				this.OnDefaultDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(50)")]
	public string Contact
	{
		get
		{
			return this._Contact;
		}
		set
		{
			if ((this._Contact != value))
			{
				this.OnContactChanging(value);
				this.SendPropertyChanging();
				this._Contact = value;
				this.SendPropertyChanged("Contact");
				this.OnContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POVendor", DbType="Bit")]
	public System.Nullable<bool> POVendor
	{
		get
		{
			return this._POVendor;
		}
		set
		{
			if ((this._POVendor != value))
			{
				this.OnPOVendorChanging(value);
				this.SendPropertyChanging();
				this._POVendor = value;
				this.SendPropertyChanged("POVendor");
				this.OnPOVendorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorNumber", DbType="VarChar(50)")]
	public string VendorNumber
	{
		get
		{
			return this._VendorNumber;
		}
		set
		{
			if ((this._VendorNumber != value))
			{
				this.OnVendorNumberChanging(value);
				this.SendPropertyChanging();
				this._VendorNumber = value;
				this.SendPropertyChanged("VendorNumber");
				this.OnVendorNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
	public string Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this.OnFaxChanging(value);
				this.SendPropertyChanging();
				this._Fax = value;
				this.SendPropertyChanged("Fax");
				this.OnFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultPODocumentCodeID", DbType="Int")]
	public System.Nullable<int> DefaultPODocumentCodeID
	{
		get
		{
			return this._DefaultPODocumentCodeID;
		}
		set
		{
			if ((this._DefaultPODocumentCodeID != value))
			{
				this.OnDefaultPODocumentCodeIDChanging(value);
				this.SendPropertyChanging();
				this._DefaultPODocumentCodeID = value;
				this.SendPropertyChanged("DefaultPODocumentCodeID");
				this.OnDefaultPODocumentCodeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCVendor", DbType="Bit NOT NULL")]
	public bool TCVendor
	{
		get
		{
			return this._TCVendor;
		}
		set
		{
			if ((this._TCVendor != value))
			{
				this.OnTCVendorChanging(value);
				this.SendPropertyChanging();
				this._TCVendor = value;
				this.SendPropertyChanged("TCVendor");
				this.OnTCVendorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedVendorTypeID", DbType="Int")]
	public System.Nullable<int> ApprovedVendorTypeID
	{
		get
		{
			return this._ApprovedVendorTypeID;
		}
		set
		{
			if ((this._ApprovedVendorTypeID != value))
			{
				this.OnApprovedVendorTypeIDChanging(value);
				this.SendPropertyChanging();
				this._ApprovedVendorTypeID = value;
				this.SendPropertyChanged("ApprovedVendorTypeID");
				this.OnApprovedVendorTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmailAddress", DbType="VarChar(100)")]
	public string ContactEmailAddress
	{
		get
		{
			return this._ContactEmailAddress;
		}
		set
		{
			if ((this._ContactEmailAddress != value))
			{
				this.OnContactEmailAddressChanging(value);
				this.SendPropertyChanging();
				this._ContactEmailAddress = value;
				this.SendPropertyChanged("ContactEmailAddress");
				this.OnContactEmailAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="Int")]
	public System.Nullable<int> CreateUserID
	{
		get
		{
			return this._CreateUserID;
		}
		set
		{
			if ((this._CreateUserID != value))
			{
				this.OnCreateUserIDChanging(value);
				this.SendPropertyChanging();
				this._CreateUserID = value;
				this.SendPropertyChanged("CreateUserID");
				this.OnCreateUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDateTime
	{
		get
		{
			return this._CreateDateTime;
		}
		set
		{
			if ((this._CreateDateTime != value))
			{
				this.OnCreateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._CreateDateTime = value;
				this.SendPropertyChanged("CreateDateTime");
				this.OnCreateDateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
